spring:
  application:
    name: tech-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/pragma_reto_reactivo_tech_db
    username: root
    password: admin
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc.core: DEBUG

server:
  port: 8081